-Weather Observation Station 3
SELECT DISTINCT CITY 
FROM STATION
WHERE ID % 2 = 0; 

- Weather Observation Station 4
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) 
FROM STATION;

- Weather Observation Station 6
SELECT CITY FROM STATION
WHERE CITY LIKE "A%" OR CITY LIKE "E%" OR CITY LIKE "I%" OR CITY LIKE "O%" OR CITY LIKE "U%";

- Weather Observation Station 10
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^.*[^AEIOU]$'
--
SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE '%a' AND CITY NOT LIKE '%e' AND CITY NOT LIKE '%i' AND CITY NOT LIKE '%o' AND CITY NOT LIKE '%u'

- Weather Observation Station 11
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[^AEIOU].*$' OR CITY REGEXP '^.*[^aeiou]$';

- Weather Observation Station 12
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '^[^AEIOU].*$' AND CITY REGEXP '^.*[^AEIOU]$';

- Higher Than 75 Marks
SELECT Name
FROM STUDENTS
WHERE Marks > 75
ORDER BY RIGHT(Name, 3), ID;


